#!/usr/bin/env node
/**
 * Generate lib/posts.ts from the crawled blog post data in .scratch/page-data.
 * Preserves title/description/canonical/OG/JSON-LD verbatim.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { JSDOM } from "jsdom";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DATA_DIR = path.join(ROOT, ".scratch/page-data");
const HTML_DIR = path.join(DATA_DIR, "html");
const CONTENT_DIR = path.join(DATA_DIR, "content");

const POST_SLUGS = JSON.parse(
  fs.readFileSync(path.join(ROOT, ".scratch/blog-post-slugs.json"), "utf8")
);

function slugFromPath(p) {
  return p.replace(/^\/|\/$/g, "");
}

/** Match the live site: always https://www.manhaironline.com */
function toWww(value) {
  if (!value || typeof value !== "string") return value;
  return value.replace(
    /https?:\/\/(?:www\.)?manhaironline\.com/gi,
    "https://www.manhaironline.com"
  );
}

const posts = [];
for (const p of POST_SLUGS) {
  const slug = slugFromPath(p);
  const dataPath = path.join(DATA_DIR, slug + ".json");
  const contentPath = path.join(CONTENT_DIR, slug + ".json");
  const htmlPath = path.join(HTML_DIR, slug + ".html");
  if (!fs.existsSync(dataPath)) {
    console.warn("MISSING data for", slug);
    continue;
  }
  const meta = JSON.parse(fs.readFileSync(dataPath, "utf8"));
  const content = fs.existsSync(contentPath)
    ? JSON.parse(fs.readFileSync(contentPath, "utf8"))
    : null;

  // Try to find a real post title (the entry-title h1 sits OUTSIDE .entry-content
  // in the Astra WP theme). Fall back to any h1 the extractor picked up.
  let heading = content?.headings?.find((h) => h.level === 1)?.text ?? null;

  // Extract post body: on Astra WP theme, the actual post content is inside
  // <div class="entry-content"> (or article .entry-content). Fall back to
  // whole main body if not present.
  let bodyHtml = null;
  let coverImage = null;
  let excerpt = null;
  let category = null;
  let datePublished = null;
  let dateModified = null;

  if (fs.existsSync(htmlPath)) {
    const html = fs.readFileSync(htmlPath, "utf8");
    const dom = new JSDOM(html);
    const doc = dom.window.document;
    // Real post title: <h1 class="entry-title" itemprop="headline">…</h1>
    const entryTitle = doc.querySelector("h1.entry-title, .entry-title");
    if (entryTitle && !heading) {
      heading = entryTitle.textContent.replace(/\s+/g, " ").trim();
    }
    const entry = doc.querySelector(".entry-content, article .entry-content");
    if (entry) {
      // Strip elementor edit buttons / navigation etc
      entry.querySelectorAll("script,style,noscript,.elementor-motion-effects-layer,.sharedaddy,.jp-relatedposts").forEach((n) => n.remove());
      bodyHtml = entry.innerHTML.trim();
      // First paragraph as excerpt
      const firstP = entry.querySelector("p");
      if (firstP) excerpt = firstP.textContent.replace(/\s+/g, " ").trim().slice(0, 200);
    }
    const featured =
      doc.querySelector('meta[property="og:image"]')?.getAttribute("content") ||
      doc.querySelector(".entry-content img")?.getAttribute("src") ||
      null;
    if (featured) coverImage = featured;
    // Category from post categories
    const cat = doc.querySelector('a[rel~="category"]');
    if (cat) category = cat.textContent.trim();
    // Dates from meta
    const pubMeta =
      doc.querySelector('meta[property="article:published_time"]')?.getAttribute("content") ||
      null;
    const modMeta =
      doc.querySelector('meta[property="article:modified_time"]')?.getAttribute("content") ||
      null;
    if (pubMeta) datePublished = pubMeta;
    if (modMeta) dateModified = modMeta;
  }

  const og = meta.og
    ? {
        ...meta.og,
        image: toWww(meta.og.image),
        url: toWww(meta.og.url),
      }
    : meta.og;

  posts.push({
    slug,
    path: p,
    title: meta.title,
    heading,
    description: meta.description,
    canonical: toWww(meta.canonical),
    robots: meta.robots,
    og,
    twitterCard: meta.twitter?.card ?? "summary_large_image",
    coverImage: toWww(coverImage),
    excerpt,
    category,
    datePublished,
    dateModified,
    bodyHtml: toWww(bodyHtml),
  });
}

// Emit TypeScript
const out = `/**
 * Blog posts inventory.
 *
 * AUTO-GENERATED by scripts/generate-posts.mjs from crawled data in
 * .scratch/page-data — DO NOT hand-edit. To refresh, re-run the script.
 *
 * Every field mirrors the live site verbatim (title, meta description,
 * canonical, OG image, body HTML, categories, dates) so SEO parity holds.
 */

export type Post = {
  slug: string;
  path: string;
  title: string;
  heading: string | null;
  description: string | null;
  canonical: string | null;
  robots: string;
  og: {
    title: string | null;
    description: string | null;
    image: string | null;
    type: string | null;
    url: string | null;
    site_name: string | null;
    locale: string | null;
  };
  twitterCard: string;
  coverImage: string | null;
  excerpt: string | null;
  category: string | null;
  datePublished: string | null;
  dateModified: string | null;
  /** Raw, sanitized WordPress \`.entry-content\` HTML. */
  bodyHtml: string | null;
};

export const POSTS: Post[] = ${JSON.stringify(posts, null, 2)};

export function getPostBySlug(slug: string): Post | undefined {
  return POSTS.find((p) => p.slug === slug);
}
`;

fs.writeFileSync(path.join(ROOT, "lib/posts.ts"), out);
console.log("wrote lib/posts.ts with", posts.length, "posts");
